### ISSUE TITLE
Reading calls file does not work with Galaxy

### ISSUE THREAD

**Issue by matnguyen** [WGS-TB/PathOGiST#3]
Since Galaxy data structures are in the form of .dat, the read_calls functions do not work.

```
if calls_path.endswith("txt"):
```

checks for files that end with .txt, but all files in Galaxy are renamed to the .dat format.

**Comment by realseanla** [comment]
Pushed a change to master. Let me know if anything needs to be changed.

**Comment by matnguyen** [comment]
Looks good to me! Thank you!
